### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by emanuelmutschlechner**
Update dependencies to latest stable version

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
thank you very much for the help, you could do another PR with the change or change this for `yarn.lock`
screenshot_62

**Comment by emanuelmutschlechner** [comment]
Do you want me to delete the .lock file?

**Comment by luisDanielRoviraContreras** [comment]
if you can delete it, it would be great, for me to add it later and that it does not form incorrectly because there are some dependencies that I want to delete and add others like scss (sass)

**Comment by emanuelmutschlechner** [comment]
Sure

**Pull request merged**
