### PR TITLE
Added Margin & Padding & Font Size Stylus Classes

### PR DESCRIPTION
**Pull request by grali**
All the above said helpers can be changed by calling a stylus function underneath.

### CODE REVIEW

**Comment by grali** [comment]
Actually this class is cleaner and more robust than the one I said in the issue but if you want that one I can make a PR for that one, too.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the contribution

**Comment by grali** [comment]
Your welcome! Do you want me to make a documentation for that?

**Comment by luisDanielRoviraContreras** [comment]
It would be great and so we are adding more without problem

**Comment by grali** [comment]
Amazing! I make a box in grid for these.

**Comment by luisDanielRoviraContreras** [comment]
It would be great but better if it integrates with the grid!

**Pull request merged**
