### PR TITLE
When vsTabs added using a v-for loop, removing from the array now removes the tab (Fix)

### PR DESCRIPTION
**Pull request by samiam9297**
When using an array to build out tabs, an entry in the array would add a new tab but a deletion in the array would not remove an existing tab. Added a destroyed function to remedy.
chrome-capture

### CODE REVIEW

**Comment by samiam9297** [comment]
@nimasfl https://github.com/lusaxweb/vuesax/pull/491

**Comment by samhk222** [comment]
Why this isn't merged yet ? I'm facing a serious problem because of that.

**Comment by daxsis** [comment]
@luisDanielRoviraContreras can we get updates on when it will be merged? I encountered the same problem which is an easy fix.

**Comment by jd-0001** [comment]
Hi, @daxsis unfortunately, I am not maintainer of this repo. :pray:

**Comment by luisDanielRoviraContreras** [comment]
remove files please only changes @samiam9297

**Comment by samiam9297** [comment]
@luisDanielRoviraContreras Done

**Comment by luisDanielRoviraContreras** [comment]
conflict dist/vuesax.common.js
dist/vuesax.umd.js
dist/vuesax.umd.min.js remove files please 
@samiam9297

**Comment by samiam9297** [comment]
First PR to an open source library.. those files were removed previously. Is there something special I need to do?
image
@luisDanielRoviraContreras

**Pull request closed without merging**
