### PR TITLE
Finished component Topbar

### PR DESCRIPTION
**Pull request by fergardi**
I know it is extremely simple, but I think we can use this component for now until a rework is proposed. It is not responsive as well. I am not sure how to achieve that without icon buttons.

We should add support for icon buttons.

image

I'm not very good with the styles & design, sorry.

### CODE REVIEW

**Comment by fergardi** [comment]
I added icon buttons and improved toolbar with them.

image

image

**Comment by fergardi** [comment]
I know it is far from useful but yes was the initial idea.

**Comment by VicGUTT** [comment]
Alright good. :)
Oh no I did not mean it in any negative or pejorative way, just genuinely wanted to know because that was the next component in my todo list ^^

**Comment by fergardi** [comment]
@VicGUTT no offense taken!

Well if you accept suggestions you could work in a closable left/right sidebar. I was considering it myself but it seems a little bit difficult for met to achieve, with the responsiveness and all.

**Comment by luisDanielRoviraContreras** [comment]
@VicGUTT @fergardi please for any new component or improve first open a issues and assign them the component or improvement to not work on the same or have some kind of problem, thank you very much

**Pull request merged**
