### PR TITLE
Finished component Card.

### PR DESCRIPTION
**Pull request by fergardi**
Here you go!

image

What do you think?

### CODE REVIEW

**Comment by periscuelo** [comment]
Hi guys. First thanks for the Framework. Where is the card colors? I can't see it in the docs

**Comment by luisDanielRoviraContreras** [comment]
@periscuelo the component was updated and there is no support for colors, it can be changed by normal css

**Comment by ibrahim-brumate** [comment]
Can you show me some example? Because i tryed change with .v-card-header {} but doesn't work. Thanks for quick reply.

**Comment by periscuelo** [comment]
Can you show me some example? Because i tryed change with .v-card-header {} but doesn't work. Thanks for quick reply.

**Comment by luisDanielRoviraContreras** [comment]
```css
.vs-card-header {
  background: #000
}
```

screenshot_60

**Comment by periscuelo** [comment]
And if i wanna a scoped css? Because with scoped css doesn't work. Your example Works only if is not a scoped css. Thanks for quick reply.

**Comment by periscuelo** [comment]
I got it. See below how to do.

CSS
`.myClass >>> .vs-card-header {
    background-color: #000;
}`

SCSS
`.myClass /deep/ .vs-card-header {
    background-color: #000;
}`

Just add `myClass` in vscard before the slot content.
`<vs-card class="myClass">`

Thanks.

**Pull request merged**
