### PR TITLE
Adjust Quickstart example in README to use updated CDN

### PR DESCRIPTION
**Pull request by williamcameron**
Adjusted the example quickstart code to use the latest and suggested unpkg CDN.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
It would make more sense to change the other link to jsDelivr instead. It's faster and recommended by vue too.

**Comment by luisDanielRoviraContreras** [comment]
@MartinKolarik which cdn you consider to be better and if you can pass the vuesax links it would be great thank you very much

**Comment by MartinKolarik** [comment]
@luisDanielRoviraContreras I updated the links in #111

**Comment by luisDanielRoviraContreras** [comment]
@MartinKolarik You could tell me why it is better one than the other or if you have some document or reference of why it is better to thank you very much for the contribution

**Comment by MartinKolarik** [comment]
@luisDanielRoviraContreras basically jsDelivr has more robust infrastructure based on four CDN providers (including Cloudflare which is used by unpkg) as described [here](https://www.jsdelivr.com/network/infographic). It's more stable and [slightly faster](https://www.cdnperf.com/) (or a lot faster, it depends on user location - e.g. it's the only public CDN that's reliable in China). You also get [usage stats](https://www.jsdelivr.com/package/npm/vuesax) which you might or might not find useful.

**Comment by williamcameron** [comment]
@MartinKolarik  Happy to go with your suggestions.  I was adjusting the code to reference the same CDN as linked to in the paragraph below it.

If there are performance improvements if a specific one is chosen, I am happy to concede and take your advice there.

Thanks,

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much @williamcameron

**Pull request closed without merging**
