### PR TITLE
Added new component Chip

### PR DESCRIPTION
**Pull request by fergardi**
There you go!

image

There is yet to do some logic with the closable emit event.

P.D: Por cierto, también hablo español ;)

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
@fergardi thank you very much this great but wait a moment that I am migrating almost all the documentation and when I upload it I approve the function to save the work I will upload what I have and I would like to thank you very much for the contribution

**Comment by fergardi** [comment]
So I stop developing you finish the migration? Or can I continue with more components?

**Comment by luisDanielRoviraContreras** [comment]
You can continue with the components without any problem but the documents if you have to wait to make them

I finished the migration but is giving me problems in the deploy gives you the same problem?

https://github.com/vuejs/vuepress/issues/371

**Comment by luisDanielRoviraContreras** [comment]
@fergardi Ready is the document implemented with vuepress please review thank you very much

**Comment by fergardi** [comment]
Okay, I will as soon as possible.

Out of curiosity, was it difficult to migrate from the previous documentation to the VuePress one? How did you do the process? How many hours of work? How did you do the previous docs? Manually or using a tool?

By the way, the docs and the overall site feels much more faster now! I miss the transitions though.

**Comment by luisDanielRoviraContreras** [comment]
Well, if it took me a lot of time like a week and it was clean, one by one

the previous documents I made with vuejs only

the documents are now easier to maintain and improve for now does not have the animations but I will be adding them

**Comment by luisDanielRoviraContreras** [comment]
Could you make an application with the new structure? it's the same in the components, anything, let me know, to help you, thank you very much

**Comment by fergardi** [comment]
I cannot compile the new repository. 

```
npm install && npm run dev
sh: vuepress: command not found
```

**Comment by luisDanielRoviraContreras** [comment]
You have to install vuepress global friend https://vuepress.vuejs.org/guide/getting-started.html

**Comment by fergardi** [comment]
That was it. And I was using nodejs6 instead of nodejs8 too.

Now it works!

**Comment by luisDanielRoviraContreras** [comment]
Great, good, anything, you let me know, I already assigned the component :+1:

**Comment by luisDanielRoviraContreras** [comment]
@fergardi there is a file called MAQUETA.md that contains the structure to start a documentation of a component check it

**Pull request closed without merging**
