### PR TITLE
vsInput date validation and improvements to vsSelect

### PR DESCRIPTION
**Pull request by pitchinnate**
Added a simple validation rule for input types `date`.

Made quite a few changes to vsSelect so that it acts more like vsInput in a form. It now has a container like vsInput and the width can be set on it. vsSelect can now be validated also just like a vsInput, for the validation I also added a vsRequired just like I added to vsInput. Can also send in a placeholder and a label, both are optional.

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
You could add an image of the result of the changes thanks

**Comment by pitchinnate** [comment]
You can see a select and a date input on this screenshot.

image

**Comment by pitchinnate** [comment]
Should be good to go now.

**Comment by luisDanielRoviraContreras** [comment]
thank you very much I will review to put it into production

**Pull request merged**
