### PR TITLE
Added missing props in vs-table for descriptions

### PR DESCRIPTION
**Pull request by tiagosimoesdev**
With the new implementation of table description https://lusaxweb.github.io/vuesax/components/table.html#description

there were no props for `description-title` ,  `description-connector` and `description-body` , now it's possible to add these so you can translate those fields. 

Also in vs-pagination added default props icons were missing.

Improved vs-table description design 
pagination

### CODE REVIEW

**Comment by jd-0001** [comment]
Hello @tiagosimoesdev Great! I was also working on the same.
Now, if I make changes then both of us get conflict maybe. So, I have tiny suggestion.
If we stick both pagination & it's description on the edges of container using `flex-start` & `flex-end`(in vs-col) it would look well aligned.

Waiting for your PR merge.

**Comment by tiagosimoesdev** [comment]
@jd-0001 yeah I have done for my project , but I'll updated it here also

**Comment by devstack-be** [comment]
is it possible to merge those changes to your master? @luisDanielRoviraContreras

**Comment by luisDanielRoviraContreras** [comment]
@devstack-be no since it has unnecessary build changes

**Comment by devstack-be** [comment]
Ok thanks for your quick answer. But i don't understand why it's unnecessary, because those props are mentionned in your docs but don't work in master version. Thanks again.

**Comment by luisDanielRoviraContreras** [comment]
the truth we are not focused on v3 and that is why we have left it aside and if the PR is not ready to do merch I can not do it

**Comment by devstack-be** [comment]
No problem i understand that. Thanks for your work.

**Pull request closed without merging**
