### PR TITLE
new type property to change button type (HTML)

### LINKED ISSUE #121: Buttton type gets ignored
After the last update, the button type could be set manually overriding Vuesax default as "button". So we could set a button to be submit using:
```
<vs-button
    type="button"
   ...
</vs-button>
```

Now the type gets ignored and the button is always set as `type="button"`. This makes forms stop working when the button calls the form submit.

- OS: Windows 10
- Node.js version: 8.11.2
- Vuesax version: vuesax3.1.7
- Browser version: Chrome 67.0.3396.87
- Package manager: npm v6.1.0

### PR DESCRIPTION
**Pull request by RickCardoso**
fixes #121

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
@RickCardoso And do not think it could be better `: type=" $attrs.type "` you could check if it works as it should and thank you very much for the contribution

or remove the `type =" button "` property of the component and by default this is not

I say it so as not to create a property that confuses the user in that sense

**Comment by RickCardoso** [comment]
I don't understand, do you already have another solution in mind?

I believe that `vs-type` was a well-intended choice for the property, but it was not a good choice, because `type` has a meaning other the "style" of the button. The ideal here it would be to have a property such as `vs-type` to define the `type` of the button (`button`, `submit`, `reset`) and a `vs-button` or `vs-style` property for `filled`, `outline`, `relief`, etc.

But that's not a good change to make right now, because it will break the users' apps.

**Comment by luisDanielRoviraContreras** [comment]
You have the absolute best reason to change the property to `vs-style` and leave the` type` property to be binded by default to the button with `: type`

**Comment by luisDanielRoviraContreras** [comment]
Please, you could close this PR and make another with only the required changes, thank you very much
screenshot_25

**Pull request closed without merging**
