### PR TITLE
Add vsSize prop for <vs-input> component

### PR DESCRIPTION
**Pull request by kaungmyatlwin**
PR is intended to add sizing for vs-input (See: #267).

`vsSize` prop is added with 3 options (type: String).

`small` for very small input size.
`normal` for normal input size.
`large` for large input size.

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
Thanks for the contribution, if you are in discord, pass your username

**Comment by kaungmyatlwin** [comment]
@luisDanielRoviraContreras It's `Lay Htoe Tan#4238`.

**Comment by kaungmyatlwin** [comment]
Weird. @luisDanielRoviraContreras can you find with the username of `layhtoetan`?

**Comment by luisDanielRoviraContreras** [comment]
screenshot_76

**Comment by kaungmyatlwin** [comment]
@luisDanielRoviraContreras Can you tell me your Discord username? I'll add ya.

**Comment by luisDanielRoviraContreras** [comment]
luisdanielroviracontreras#5677

**Pull request merged**
