### PR TITLE
Add icon library support

### PR DESCRIPTION
**Pull request by Jacrys**
Made required changes to code

### CODE REVIEW

**Comment by brunokunace** [comment]
@Jacrys you can remove this conflicts?

ty

**Comment by brunokunace** [comment]
@Jacrys hi hi, can you resolve this conflicts?

**Comment by Jacrys** [comment]
Sorry @brunokunace, this hung for a while, I wasn't getting GH notifications for a time, and I have been dealing with tight deadlines at work.  I have some leave coming up in the next week, and will get on this when I get a chance.

**Comment by brunokunace** [comment]
any news with conflict?

**Comment by Jacrys** [comment]
@brunokunace @luisDanielRoviraContreras all conflicts should be resolved.  I apologize for the time this took me. I have rebased this on master, so all current live changes should be present. I would rather someone look over this quickly than merge myself.

**Pull request merged**
