### PR TITLE
Added the Breadcrumb component

### PR DESCRIPTION
**Pull request by VicGUTT**
Small but useful component

### CODE REVIEW

**Comment by luisDanielRoviraContreras** [comment]
Please add a capture of the component and thank you very much for the contribution

**Comment by VicGUTT** [comment]
Ooh yeah I forgot sorry.
There you go :
components_breadcrumb html

**Comment by luisDanielRoviraContreras** [comment]
Wow, it's really great, thank you very much, please resolve the conflicts so that the entire request is yours and include yourself in the contributors. You may have seen it last.

**Comment by luisDanielRoviraContreras** [comment]
@VicGUTT profavor resolves the conflict so that your contribution is added to vuesax, I would like it but I want you to earn the credit for the contribution you have made

**Comment by VicGUTT** [comment]
Sure thing, imma get into it :)

**Pull request merged**
