### PR TITLE
Added the pagination component

### PR DESCRIPTION
**Pull request by VicGUTT**
Hi guys, sorry it took me so long, i'm pretty busy with work right now.
Anyway, I created the pagination component. Next component will probably be the navbar. When I'm sure I will create an issue suggesting the add so I can be assinged to create it.

Cheers.

### CODE REVIEW

**Comment by VicGUTT** [comment]
Sure, there you go :
components_pagination html

**Comment by VicGUTT** [comment]
Ps.: I wanted to add a directive similar to `vs-theme` with parameters like **primary**, **default** or **custom** *which would be a HEX value* but I was having a hard time getting Stylus to handle CSS "Custom properties" *aka* CSS variables. I wanted to use CSS variables for consistency since the code base primarily  use those.
If anyone knows how let me know, first timer with stylus here ^^

Ps. bis : I know I previously said I'd work on translating and make the framework more "accessibility compliant" but that is such a cumbersome and pretty annoying task to do. And the master branch commits goes way to fast aha ^^. I'll probably get into it later.

**Comment by luisDanielRoviraContreras** [comment]
Wow I am super great thank you very much for creating the component I will review it to upload it to production thank you very much and it is very good idea to address that topic later

**Comment by luisDanielRoviraContreras** [comment]
@VicGUTT The added component is already in production and thanks for the contribution 👍

**Comment by luisDanielRoviraContreras** [comment]
@VicGUTT Friend, I do not know why you do not add in contributions from Vuesax, I do not understand it, I'll add you in the documentation. Sorry for this, I do not know why it's happening

**Comment by VicGUTT** [comment]
@luisDanielRoviraContreras  Thanks for adding to `vs-color` directive.

@fergardi I used Chrome dev tools.
You can reproduce it by following those steps : Open the dev tools > Toggle the device toolbar > Top right corner click on the options (vertical 3 dots) > Finally click on **Capture full size screenshot**. That should do the trick

**Comment by fergardi** [comment]
@VicGUTT didn't know at all. Many thanks!

**Comment by VicGUTT** [comment]
@fergardi You're welcome, happy to help.

**Comment by luisDanielRoviraContreras** [comment]
@VicGUTT I found the solution to be able to use the css variables within the stylus

```
@css{
  .con-init ul li:hover {
    background: rgb(var(--primary));
    color: rgb(255, 255, 255);
  }
}
```
to be able to use the variables you have to contain them within @css and ready thanks for the contribution to vuesax

**Comment by VicGUTT** [comment]
Nice, thank you for the tip 👍
I hope I will be able to contribute a little more to the project around next week-end.

**Pull request merged**
